# Generated by Django 4.0 on 2022-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
