# Generated by Django 4.0 on 2022-11-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0008_contact_email_contact_mobile_contact_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='classname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='danceapp.class'),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
