# Generated by Django 4.0 on 2022-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0010_registration_message_registration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, default='New', max_length=100, null=True),
        ),
    ]
