# Generated by Django 4.0 on 2022-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0016_remove_registration_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment',
            field=models.CharField(blank=True, default='New', max_length=100, null=True),
        ),
    ]
