# Generated by Django 4.0 on 2022-12-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0017_registration_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment',
        ),
    ]
