# Generated by Django 4.0 on 2022-12-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0026_remove_registration_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='classname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='danceapp.class'),
        ),
    ]
