# Generated by Django 4.0 on 2022-12-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0028_remove_trackinghistory_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
