# Generated by Django 4.0.2 on 2022-12-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0030_trackinghistory_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='trackinghistory',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='trackinghistory',
            name='paymentmode',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='danceapp.registration')),
            ],
        ),
    ]
